apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-lotus-api"
  namespace: {{ .Release.Name }}
  labels:
    app: lotus-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lotus-api
  template:
    metadata:
      labels:
        app: lotus-api
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP