replicaCount: 2

image:
  repository: luizlipefs/server
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  name: lotus-service
  type: ClusterIP
  port: 3005
  targetPort: 3005

env:
  name: seu-banco

jobs:
  repository: luizlipefs/jobs
  tag: "1.0.2"
  list:
    - name: renovacao-cesta
      entrypoint: enovacao-cesta
      cron: "* * * * *"
    - name: transacoes-pendentes
      entrypoint: transacoes-pendentes
      cron: "*/2 * * * *"